// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLXUQ6S5Jvrl173fOXTKx2K3PmWvKBA4Y',
    appId: '1:818112359670:web:58b4bac2bd616986a1d0d7',
    messagingSenderId: '818112359670',
    projectId: 'carsnap-9ea99',
    authDomain: 'carsnap-9ea99.firebaseapp.com',
    storageBucket: 'carsnap-9ea99.appspot.com',
    measurementId: 'G-3CS0GNRYG7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIR-bFYO-TAb64OcSIPDPsY4RNRgQcNbU',
    appId: '1:818112359670:android:e276df1dc1020cb2a1d0d7',
    messagingSenderId: '818112359670',
    projectId: 'carsnap-9ea99',
    storageBucket: 'carsnap-9ea99.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7fBaqZ0mASERb09w1ypi15sSzohBCJGo',
    appId: '1:818112359670:ios:3e4eab993dc12497a1d0d7',
    messagingSenderId: '818112359670',
    projectId: 'carsnap-9ea99',
    storageBucket: 'carsnap-9ea99.appspot.com',
    iosBundleId: 'com.example.carsnap',
  );

}